import {
    Document,
    Page,
    Text,
    View,
    StyleSheet,
    Font,
} from '@react-pdf/renderer';

// Register standard fonts to ensure consistent rendering
Font.register({
    family: 'Helvetica-Bold',
    src: 'Helvetica-Bold',
});

const styles = StyleSheet.create({
    page: {
        padding: 40,
        backgroundColor: '#FFFFFF',
        fontFamily: 'Helvetica',
        position: 'relative',
    },
    watermarkContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: -1,
        opacity: 0.1,
    },
    watermarkText: {
        fontSize: 60,
        color: '#000000',
        transform: 'rotate(-45deg)',
        fontFamily: 'Helvetica-Bold',
    },
    header: {
        marginBottom: 30,
        borderBottom: '2px solid #0F766E',
        paddingBottom: 20,
    },
    title: {
        fontSize: 28,
        fontFamily: 'Helvetica-Bold',
        color: '#0A0A0A',
        marginBottom: 10,
    },
    subtitle: {
        fontSize: 14,
        color: '#666666',
    },
    sectionTitle: {
        fontSize: 18,
        fontFamily: 'Helvetica-Bold',
        color: '#0F766E',
        marginTop: 20,
        marginBottom: 15,
    },
    textBody: {
        fontSize: 11,
        lineHeight: 1.6,
        color: '#333333',
        marginBottom: 10,
    },
    summaryBox: {
        backgroundColor: '#F8F8F8',
        padding: 15,
        borderRadius: 4,
        marginBottom: 20,
    },
    summaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    summaryLabel: {
        fontSize: 10,
        color: '#666666',
        textTransform: 'uppercase',
    },
    summaryValue: {
        fontSize: 12,
        fontFamily: 'Helvetica-Bold',
        color: '#0A0A0A',
    },
    // Table Styles
    table: {
        display: 'flex',
        flexDirection: 'column',
        width: 'auto',
        marginTop: 10,
        borderStyle: 'solid',
        borderWidth: 1,
        borderColor: '#E5E5E5',
    },
    tableRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E5E5',
    },
    tableHeaderRow: {
        backgroundColor: '#F8F8F8',
        fontFamily: 'Helvetica-Bold',
    },
    tableColChannel: {
        width: '40%',
        padding: 8,
        borderRightWidth: 1,
        borderRightColor: '#E5E5E5',
    },
    tableColNumber: {
        width: '20%',
        padding: 8,
        borderRightWidth: 1,
        borderRightColor: '#E5E5E5',
        textAlign: 'right',
    },
    tableColNotes: {
        width: '20%',
        padding: 8,
    },
    tableCellHeader: {
        fontSize: 10,
        color: '#666666',
    },
    tableCell: {
        fontSize: 10,
        color: '#333333',
    },
    tableCellBold: {
        fontSize: 10,
        fontFamily: 'Helvetica-Bold',
        color: '#0A0A0A',
    },
    rationaleItem: {
        marginBottom: 15,
    },
    rationaleChannel: {
        fontSize: 12,
        fontFamily: 'Helvetica-Bold',
        color: '#0A0A0A',
        marginBottom: 4,
    },
    rationaleText: {
        fontSize: 10,
        lineHeight: 1.5,
        color: '#333333',
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderTop: '1px solid #E5E5E5',
        paddingTop: 10,
    },
    footerText: {
        fontSize: 8,
        color: '#999999',
    }
});

interface Allocation {
    channel: string;
    percentage: number;
    budget_gbp: number;
    rationale: string;
}

interface PlanData {
    campaign_name: string;
    total_budget_gbp: number;
    allocation: Allocation[];
    overlaps_q4: boolean;
    requires_agency: boolean;
    contains_broadcast: boolean;
    overall_rationale: string;
}

interface PDFProps {
    plan: PlanData;
    isFreeTier?: boolean;
}

const Watermark = () => (
    <View style={styles.watermarkContainer} fixed>
        <Text style={styles.watermarkText}>FREE TIER PREVIEW</Text>
    </View>
);

const Footer = () => (
    <View style={styles.footer} fixed>
        <Text style={styles.footerText}>Generated by MediaMind Strategist Agent</Text>
        <Text style={styles.footerText} render={({ pageNumber, totalPages }) => (`Page ${pageNumber} of ${totalPages}`)} />
    </View>
);

export default function MediaPlanPDF({ plan, isFreeTier = true }: PDFProps) {
    const sortedAlloc = [...plan.allocation].sort((a, b) => b.percentage - a.percentage);

    return (
        <Document>
            {/* PAGE 1: Executive Summary */}
            <Page size="A4" style={styles.page}>
                {isFreeTier && <Watermark />}
                <View style={styles.header}>
                    <Text style={styles.title}>{plan.campaign_name}</Text>
                    <Text style={styles.subtitle}>Media Strategy Recommendation</Text>
                </View>

                <View style={styles.summaryBox}>
                    <View style={styles.summaryRow}>
                        <Text style={styles.summaryLabel}>Total Budget</Text>
                        <Text style={styles.summaryValue}>£{plan.total_budget_gbp.toLocaleString()}</Text>
                    </View>
                    <View style={styles.summaryRow}>
                        <Text style={styles.summaryLabel}>Total Channels</Text>
                        <Text style={styles.summaryValue}>{plan.allocation.length}</Text>
                    </View>
                    <View style={styles.summaryRow}>
                        <Text style={styles.summaryLabel}>Agency Required</Text>
                        <Text style={styles.summaryValue}>{plan.requires_agency ? 'Yes' : 'No'}</Text>
                    </View>
                </View>

                <Text style={styles.sectionTitle}>Executive Rationale</Text>
                <Text style={styles.textBody}>{plan.overall_rationale}</Text>

                {plan.overlaps_q4 && (
                    <View style={{ ...styles.summaryBox, backgroundColor: '#FEF3C7', marginTop: 20 }}>
                        <Text style={{ ...styles.summaryLabel, color: '#B45309' }}>Q4 Seasonality Alert</Text>
                        <Text style={{ ...styles.textBody, color: '#B45309', marginTop: 5 }}>
                            This campaign targets the 'Golden Quarter' (Q4). Digital CPMs will be significantly elevated, and broadcast inventory will be highly contested.
                        </Text>
                    </View>
                )}

                <Footer />
            </Page>

            {/* PAGE 2: Media Mix Breakdown */}
            <Page size="A4" style={styles.page}>
                {isFreeTier && <Watermark />}
                <Text style={styles.sectionTitle}>Budget Allocation Breakdown</Text>

                <View style={styles.table}>
                    {/* Header */}
                    <View style={[styles.tableRow, styles.tableHeaderRow]}>
                        <View style={styles.tableColChannel}>
                            <Text style={styles.tableCellHeader}>Channel</Text>
                        </View>
                        <View style={styles.tableColNumber}>
                            <Text style={styles.tableCellHeader}>Mix %</Text>
                        </View>
                        <View style={styles.tableColNumber}>
                            <Text style={styles.tableCellHeader}>Investment (£)</Text>
                        </View>
                        <View style={styles.tableColNotes}>
                            <Text style={styles.tableCellHeader}>Format Type</Text>
                        </View>
                    </View>

                    {/* Rows */}
                    {sortedAlloc.map((alloc, idx) => {
                        const isBroadcast = ['Linear TV', 'Commercial Radio', 'DOOH (Digital Outdoor)'].includes(alloc.channel);
                        return (
                            <View key={idx} style={styles.tableRow}>
                                <View style={styles.tableColChannel}>
                                    <Text style={styles.tableCellBold}>{alloc.channel}</Text>
                                </View>
                                <View style={styles.tableColNumber}>
                                    <Text style={styles.tableCell}>{alloc.percentage.toFixed(1)}%</Text>
                                </View>
                                <View style={styles.tableColNumber}>
                                    <Text style={styles.tableCellBold}>£{alloc.budget_gbp.toLocaleString()}</Text>
                                </View>
                                <View style={styles.tableColNotes}>
                                    <Text style={styles.tableCell}>{isBroadcast ? 'Broadcast' : 'Digital'}</Text>
                                </View>
                            </View>
                        );
                    })}
                </View>

                {plan.contains_broadcast && (
                    <View style={{ marginTop: 20 }}>
                        <Text style={styles.sectionTitle}>Broadcast Implementation Notes</Text>
                        <Text style={styles.textBody}>
                            The inclusion of broadcast channels (TV, Radio, or Outdoor) requires external agency orchestration for media buying and creative dispatch (e.g., Clearcast approval and delivery via Peach). These channels cannot be automatically deployed via the MediaMind Watchdog.
                        </Text>
                    </View>
                )}

                <Footer />
            </Page>

            {/* PAGE 3: Detailed Rationale */}
            <Page size="A4" style={styles.page}>
                {isFreeTier && <Watermark />}
                <Text style={styles.sectionTitle}>Channel Rationale</Text>

                {sortedAlloc.map((alloc, idx) => (
                    <View key={idx} style={styles.rationaleItem}>
                        <Text style={styles.rationaleChannel}>{alloc.channel}</Text>
                        <Text style={styles.rationaleText}>{alloc.rationale}</Text>
                    </View>
                ))}

                <Footer />
            </Page>
        </Document>
    );
}
